name: learncleanarch
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # service locator
  get_it: ^4.0.2
  # state
  flutter_bloc: ^4.0.0
  # object equality
  equatable: ^1.2.0
  # functional programming
  dartz: ^0.9.1
  # network state
  connectivity: ^0.4.8+6
  # remote call
  http: ^0.12.1
  # local key cache
  shared_preferences: ^0.5.7+3

  # moor
  moor_flutter: ^3.0.0
  # chopper
  chopper: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mocking
  mockito: ^4.1.1
  build_runner:
  moor_generator: ^3.1.0
  chopper_generator: ^2.0.0




flutter:

  uses-material-design: true

